-- =============================================================================
-- Westeros (Neptune's Pride GOT) — Full Schema
-- Generated: 2026-05-21
-- Run this on a fresh Postgres instance to recreate all tables, constraints,
-- and indexes. Execute before seed.sql, functions.sql, and policies.sql.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions (Supabase enables these by default; include for completeness)
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- =============================================================================
-- USER PROFILES
-- =============================================================================

CREATE TABLE profiles (
  user_id      uuid        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text        NOT NULL DEFAULT '',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION update_profiles_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_profiles_updated_at();


-- =============================================================================
-- STATIC / REFERENCE TABLES
-- (No game_id FK — seeded once, read-only during play)
-- =============================================================================

-- ---------------------------------------------------------------------------
-- houses
-- ---------------------------------------------------------------------------
CREATE TABLE houses (
  slug             text        PRIMARY KEY,
  name             text        NOT NULL,
  words            text,
  color            text        NOT NULL,
  seat_castle_slug text        NOT NULL,
  head_of_house    text
);

-- ---------------------------------------------------------------------------
-- castles
-- ---------------------------------------------------------------------------
CREATE TABLE castles (
  slug              text             PRIMARY KEY,
  name              text             NOT NULL,
  region            text             NOT NULL,
  tier              integer          NOT NULL,
  base_influence    integer          NOT NULL DEFAULT 10,
  map_x             double precision NOT NULL,
  map_y             double precision NOT NULL,
  ruling_house_slug text,
  CONSTRAINT castles_tier_check CHECK (tier = ANY (ARRAY[1, 2, 3])),
  CONSTRAINT castles_ruling_house_slug_fkey FOREIGN KEY (ruling_house_slug) REFERENCES houses (slug)
);

CREATE INDEX idx_castles_region ON castles USING btree (region);
CREATE INDEX idx_castles_tier   ON castles USING btree (tier);

-- ---------------------------------------------------------------------------
-- house_starting_castles
-- ---------------------------------------------------------------------------
CREATE TABLE house_starting_castles (
  house_slug  text    NOT NULL,
  castle_slug text    NOT NULL,
  is_seat     boolean NOT NULL DEFAULT false,
  PRIMARY KEY (house_slug, castle_slug),
  CONSTRAINT house_starting_castles_house_slug_fkey  FOREIGN KEY (house_slug)  REFERENCES houses  (slug),
  CONSTRAINT house_starting_castles_castle_slug_fkey FOREIGN KEY (castle_slug) REFERENCES castles (slug)
);

-- ---------------------------------------------------------------------------
-- house_ai_personality
-- ---------------------------------------------------------------------------
CREATE TABLE house_ai_personality (
  house_slug      text             PRIMARY KEY,
  troop_bias      numeric          NOT NULL DEFAULT 1.0,
  atk_bias        numeric          NOT NULL DEFAULT 1.0,
  focus_override  text,
  expand_bias     integer          NOT NULL DEFAULT 1,
  flavor_note     text
);

-- ---------------------------------------------------------------------------
-- commander_pool  (named commanders assignable per house)
-- ---------------------------------------------------------------------------
CREATE TABLE commander_pool (
  id              bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house_slug      text    NOT NULL,
  name            text    NOT NULL,
  is_head_of_house boolean NOT NULL DEFAULT false,
  CONSTRAINT commander_pool_house_slug_fkey FOREIGN KEY (house_slug) REFERENCES houses (slug)
);

CREATE INDEX idx_commander_pool_house ON commander_pool USING btree (house_slug);


-- =============================================================================
-- GAME LIFECYCLE TABLES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- games
-- ---------------------------------------------------------------------------
CREATE TABLE games (
  id                       bigint                   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                     text                     NOT NULL,
  status                   text                     NOT NULL,
  tick_speed               text                     NOT NULL,
  balance_mode             text                     NOT NULL DEFAULT 'standard',
  max_players              integer                  NOT NULL DEFAULT 9,
  fill_with_ai             boolean                  NOT NULL DEFAULT true,
  win_conditions           jsonb                    NOT NULL DEFAULT '{}',
  created_by               uuid,
  created_at               timestamptz              NOT NULL DEFAULT now(),
  started_at               timestamptz,
  ended_at                 timestamptz,
  current_tick             integer                  NOT NULL DEFAULT 0,
  last_tick_processed_at   timestamptz,
  winner_player_id         bigint,
  turn_timeout_hours       integer                  NOT NULL DEFAULT 24,
  ai_difficulty            integer                  NOT NULL DEFAULT 3,
  victory_pct              numeric                  NOT NULL DEFAULT 0.50,
  starting_gold            integer                  NOT NULL DEFAULT 500,
  starting_garrison        integer                  NOT NULL DEFAULT 10,
  starting_gold_level      integer                  NOT NULL DEFAULT 10,
  starting_industry_level  integer                  NOT NULL DEFAULT 5,
  starting_prestige_level  integer                  NOT NULL DEFAULT 2,
  fog_of_war               boolean                  NOT NULL DEFAULT false,
  production_cycle_ticks   integer                  NOT NULL DEFAULT 12,
  commander_speed_mult     numeric                  NOT NULL DEFAULT 1.0,
  infra_cost_mult          numeric                  NOT NULL DEFAULT 1.0,
  council_cost_mult        numeric                  NOT NULL DEFAULT 1.0,
  ticks_per_turn           integer                           DEFAULT 1,
  turn_timeout_minutes     integer                           DEFAULT 1440,
  current_turn_ends_at     timestamptz,
  CONSTRAINT games_status_check       CHECK (status      = ANY (ARRAY['lobby','active','paused','finished','cancelled'])),
  CONSTRAINT games_tick_speed_check   CHECK (tick_speed  = ANY (ARRAY['slow','normal','fast','quad','turn_based'])),
  CONSTRAINT games_balance_mode_check CHECK (balance_mode = ANY (ARRAY['standard','expansion','compressed'])),
  CONSTRAINT games_max_players_check  CHECK ((max_players >= 2) AND (max_players <= 9)),
  -- created_by references auth.users (Supabase managed)
  CONSTRAINT games_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users (id)
);

CREATE INDEX idx_games_status     ON games USING btree (status);
CREATE INDEX idx_games_created_by ON games USING btree (created_by);

-- ---------------------------------------------------------------------------
-- game_players
-- ---------------------------------------------------------------------------
CREATE TABLE game_players (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint      NOT NULL,
  user_id             uuid,
  is_ai               boolean     NOT NULL DEFAULT false,
  ai_profile          text,
  house_slug          text        NOT NULL,
  display_name        text,
  is_pretender        boolean     NOT NULL DEFAULT false,
  gold                integer     NOT NULL DEFAULT 0,
  joined_at           timestamptz NOT NULL DEFAULT now(),
  eliminated_at_tick  integer,
  prestige            integer     NOT NULL DEFAULT 0,
  research_seat       text,
  next_research_seat  text,
  ai_difficulty       integer,
  turn_submitted      boolean              DEFAULT false,
  turn_submitted_at   timestamptz,
  ai_rationality      numeric              DEFAULT 0.5,
  ai_honor            numeric              DEFAULT 0.5,
  ai_greed            numeric              DEFAULT 0.5,
  ai_vengefulness     numeric              DEFAULT 0.5,
  CONSTRAINT game_players_game_id_fkey   FOREIGN KEY (game_id)    REFERENCES games  (id),
  CONSTRAINT game_players_user_id_fkey   FOREIGN KEY (user_id)    REFERENCES auth.users (id),
  CONSTRAINT game_players_house_slug_fkey FOREIGN KEY (house_slug) REFERENCES houses (slug),
  CONSTRAINT game_players_game_id_user_id_key   UNIQUE (game_id, user_id),
  CONSTRAINT game_players_game_id_house_slug_key UNIQUE (game_id, house_slug)
);

-- Add the winner FK now that game_players exists
ALTER TABLE games
  ADD CONSTRAINT fk_games_winner FOREIGN KEY (winner_player_id) REFERENCES game_players (id);

CREATE INDEX idx_game_players_game ON game_players USING btree (game_id);
CREATE INDEX idx_game_players_user ON game_players USING btree (user_id);


-- =============================================================================
-- PER-GAME STATE TABLES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- game_castles
-- ---------------------------------------------------------------------------
CREATE TABLE game_castles (
  id                  bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint   NOT NULL,
  castle_slug         text     NOT NULL,
  owner_player_id     bigint,
  gold_level          integer  NOT NULL DEFAULT 0,
  industry_level      integer  NOT NULL DEFAULT 0,
  prestige_level      integer  NOT NULL DEFAULT 0,
  troops              integer  NOT NULL DEFAULT 0,
  base_influence      integer  NOT NULL,
  effective_influence integer  NOT NULL,
  is_under_siege      boolean  NOT NULL DEFAULT false,
  siege_started_at_tick integer,
  troop_progress      numeric  NOT NULL DEFAULT 0,
  troop_accumulator   numeric           DEFAULT 0,
  has_kings_road      boolean  NOT NULL DEFAULT false,
  CONSTRAINT game_castles_game_id_castle_slug_key UNIQUE (game_id, castle_slug),
  CONSTRAINT game_castles_game_id_fkey         FOREIGN KEY (game_id)         REFERENCES games       (id),
  CONSTRAINT game_castles_castle_slug_fkey     FOREIGN KEY (castle_slug)     REFERENCES castles     (slug),
  CONSTRAINT game_castles_owner_player_id_fkey FOREIGN KEY (owner_player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_game_castles_game  ON game_castles USING btree (game_id);
CREATE INDEX idx_game_castles_owner ON game_castles USING btree (owner_player_id);

-- ---------------------------------------------------------------------------
-- commanders
-- ---------------------------------------------------------------------------
CREATE TABLE commanders (
  id                  bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint  NOT NULL,
  owner_player_id     bigint  NOT NULL,
  name                text    NOT NULL,
  is_named            boolean NOT NULL DEFAULT false,
  level               integer NOT NULL DEFAULT 1,
  experience          integer NOT NULL DEFAULT 0,
  current_castle_slug text,
  troops              integer NOT NULL DEFAULT 0,
  status              text    NOT NULL DEFAULT 'idle',
  CONSTRAINT commanders_status_check CHECK (status = ANY (ARRAY['idle','moving','sieging','dead'])),
  CONSTRAINT commanders_game_id_fkey             FOREIGN KEY (game_id)             REFERENCES games       (id),
  CONSTRAINT commanders_owner_player_id_fkey     FOREIGN KEY (owner_player_id)     REFERENCES game_players (id),
  CONSTRAINT commanders_current_castle_slug_fkey FOREIGN KEY (current_castle_slug) REFERENCES castles      (slug)
);

CREATE INDEX idx_commanders_game_owner ON commanders USING btree (game_id, owner_player_id);
CREATE INDEX idx_commanders_location   ON commanders USING btree (current_castle_slug);

-- ---------------------------------------------------------------------------
-- commander_movements
-- ---------------------------------------------------------------------------
CREATE TABLE commander_movements (
  id                bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commander_id      bigint  NOT NULL,
  game_id           bigint  NOT NULL,
  from_castle_slug  text    NOT NULL,
  to_castle_slug    text    NOT NULL,
  departed_at_tick  integer NOT NULL,
  arrives_at_tick   integer NOT NULL,
  troops            integer NOT NULL,
  march_type        text    NOT NULL DEFAULT 'assault',
  CONSTRAINT commander_movements_commander_id_fkey      FOREIGN KEY (commander_id)      REFERENCES commanders (id),
  CONSTRAINT commander_movements_game_id_fkey           FOREIGN KEY (game_id)           REFERENCES games      (id),
  CONSTRAINT commander_movements_from_castle_slug_fkey  FOREIGN KEY (from_castle_slug)  REFERENCES castles    (slug),
  CONSTRAINT commander_movements_to_castle_slug_fkey    FOREIGN KEY (to_castle_slug)    REFERENCES castles    (slug)
);

CREATE INDEX idx_movements_game    ON commander_movements USING btree (game_id);
CREATE INDEX idx_movements_arrival ON commander_movements USING btree (arrives_at_tick);

-- ---------------------------------------------------------------------------
-- commander_routes
-- ---------------------------------------------------------------------------
CREATE TABLE commander_routes (
  id            bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commander_id  bigint  NOT NULL,
  game_id       bigint  NOT NULL,
  waypoints     jsonb   NOT NULL,
  current_idx   integer NOT NULL DEFAULT 0,
  is_loop       boolean NOT NULL DEFAULT false,
  status        text    NOT NULL DEFAULT 'active',
  CONSTRAINT commander_routes_status_check CHECK (status = ANY (ARRAY['active','completed','cancelled'])),
  CONSTRAINT commander_routes_commander_id_fkey FOREIGN KEY (commander_id) REFERENCES commanders (id),
  CONSTRAINT commander_routes_game_id_fkey      FOREIGN KEY (game_id)      REFERENCES games      (id)
);

CREATE INDEX idx_routes_commander ON commander_routes USING btree (commander_id, status);
CREATE INDEX idx_routes_game      ON commander_routes USING btree (game_id, status);

-- ---------------------------------------------------------------------------
-- commander_battles
-- ---------------------------------------------------------------------------
CREATE TABLE commander_battles (
  id            bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id       bigint      NOT NULL,
  commander_id  bigint      NOT NULL,
  tick          integer     NOT NULL,
  result        text        NOT NULL,
  castle_slug   text,
  troops_sent   integer,
  troops_faced  integer,
  created_at    timestamptz DEFAULT now(),
  CONSTRAINT commander_battles_result_check    CHECK (result = ANY (ARRAY['victory','defeat'])),
  CONSTRAINT commander_battles_game_id_fkey    FOREIGN KEY (game_id)      REFERENCES games      (id),
  CONSTRAINT commander_battles_commander_id_fkey FOREIGN KEY (commander_id) REFERENCES commanders (id)
);

CREATE INDEX idx_commander_battles_commander ON commander_battles USING btree (commander_id, tick DESC);

-- ---------------------------------------------------------------------------
-- council_seats
-- ---------------------------------------------------------------------------
CREATE TABLE council_seats (
  id                bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id           bigint  NOT NULL,
  player_id         bigint  NOT NULL,
  seat              text    NOT NULL,
  level             integer NOT NULL DEFAULT 0,
  research_progress integer NOT NULL DEFAULT 0,
  CONSTRAINT council_seats_seat_check CHECK (seat = ANY (ARRAY['hand','coin','lord_commander','whisperers','grand_maester','laws','horses'])),
  CONSTRAINT council_seats_game_id_player_id_seat_key UNIQUE (game_id, player_id, seat),
  CONSTRAINT council_seats_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT council_seats_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_council_game_player ON council_seats USING btree (game_id, player_id);

-- ---------------------------------------------------------------------------
-- diplomacy
-- ---------------------------------------------------------------------------
CREATE TABLE diplomacy (
  id                          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id                     bigint  NOT NULL,
  player_a_id                 bigint  NOT NULL,
  player_b_id                 bigint  NOT NULL,
  status                      text    NOT NULL,
  status_changed_at_tick      integer,
  alliance_break_ticks_remaining integer,
  proposed_by_player_id       bigint,
  opinion_score               numeric          DEFAULT 0,
  CONSTRAINT diplomacy_check        CHECK (player_a_id < player_b_id),
  CONSTRAINT diplomacy_status_check CHECK (status = ANY (ARRAY['neutral','ally','enemy'])),
  CONSTRAINT diplomacy_game_id_player_a_id_player_b_id_key UNIQUE (game_id, player_a_id, player_b_id),
  CONSTRAINT diplomacy_game_id_fkey            FOREIGN KEY (game_id)            REFERENCES games       (id),
  CONSTRAINT diplomacy_player_a_id_fkey        FOREIGN KEY (player_a_id)        REFERENCES game_players (id),
  CONSTRAINT diplomacy_player_b_id_fkey        FOREIGN KEY (player_b_id)        REFERENCES game_players (id),
  CONSTRAINT diplomacy_proposed_by_player_id_fkey FOREIGN KEY (proposed_by_player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_diplomacy_game ON diplomacy USING btree (game_id);
CREATE INDEX idx_diplomacy_a    ON diplomacy USING btree (player_a_id);
CREATE INDEX idx_diplomacy_b    ON diplomacy USING btree (player_b_id);


-- =============================================================================
-- COMMUNICATION TABLES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- game_chat  (public in-game chat)
-- ---------------------------------------------------------------------------
CREATE TABLE game_chat (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id     bigint      NOT NULL,
  player_id   bigint      NOT NULL,
  message     text        NOT NULL,
  tick        integer     NOT NULL DEFAULT 0,
  created_at  timestamptz DEFAULT now(),
  CONSTRAINT game_chat_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT game_chat_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX game_chat_game_id_created_at ON game_chat USING btree (game_id, created_at);

-- ---------------------------------------------------------------------------
-- ravens  (private player-to-player or broadcast messages)
-- ---------------------------------------------------------------------------
CREATE TABLE ravens (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint      NOT NULL,
  sender_player_id    bigint,
  recipient_player_id bigint,
  is_broadcast        boolean     NOT NULL DEFAULT false,
  sent_at_tick        integer     NOT NULL,
  sent_at             timestamptz NOT NULL DEFAULT now(),
  subject             text,
  body                text        NOT NULL,
  is_read             boolean     NOT NULL DEFAULT false,
  CONSTRAINT ravens_game_id_fkey             FOREIGN KEY (game_id)             REFERENCES games       (id),
  CONSTRAINT ravens_sender_player_id_fkey    FOREIGN KEY (sender_player_id)    REFERENCES game_players (id),
  CONSTRAINT ravens_recipient_player_id_fkey FOREIGN KEY (recipient_player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_ravens_game      ON ravens USING btree (game_id);
CREATE INDEX idx_ravens_recipient ON ravens USING btree (recipient_player_id);

-- ---------------------------------------------------------------------------
-- message_threads  (threaded diplomatic messages)
-- ---------------------------------------------------------------------------
CREATE TABLE message_threads (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id     bigint      NOT NULL,
  subject     text,
  created_by  bigint      NOT NULL,
  created_at  timestamptz DEFAULT now(),
  CONSTRAINT message_threads_game_id_fkey    FOREIGN KEY (game_id)    REFERENCES games       (id),
  CONSTRAINT message_threads_created_by_fkey FOREIGN KEY (created_by) REFERENCES game_players (id)
);

CREATE INDEX message_threads_game_id ON message_threads USING btree (game_id);

-- ---------------------------------------------------------------------------
-- thread_participants
-- ---------------------------------------------------------------------------
CREATE TABLE thread_participants (
  thread_id  bigint NOT NULL,
  player_id  bigint NOT NULL,
  PRIMARY KEY (thread_id, player_id),
  CONSTRAINT thread_participants_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads (id),
  CONSTRAINT thread_participants_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players    (id)
);

-- ---------------------------------------------------------------------------
-- thread_messages
-- ---------------------------------------------------------------------------
CREATE TABLE thread_messages (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id   bigint      NOT NULL,
  player_id   bigint      NOT NULL,
  message     text        NOT NULL,
  tick        integer     NOT NULL DEFAULT 0,
  created_at  timestamptz DEFAULT now(),
  CONSTRAINT thread_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads (id),
  CONSTRAINT thread_messages_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players    (id)
);

CREATE INDEX thread_messages_thread_id_created_at ON thread_messages USING btree (thread_id, created_at);


-- =============================================================================
-- INTEL / EVENT / LEDGER TABLES
-- =============================================================================

-- ---------------------------------------------------------------------------
-- game_events
-- ---------------------------------------------------------------------------
CREATE TABLE game_events (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id     bigint      NOT NULL,
  tick        integer     NOT NULL,
  event_type  text        NOT NULL,
  player_id   bigint,
  data        jsonb       NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT game_events_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT game_events_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_events_game_tick ON game_events USING btree (game_id, tick);
CREATE INDEX idx_events_type      ON game_events USING btree (event_type);

-- ---------------------------------------------------------------------------
-- player_inbox  (per-player notifications/reports)
-- ---------------------------------------------------------------------------
CREATE TABLE player_inbox (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id     bigint      NOT NULL,
  player_id   bigint      NOT NULL,
  tick        integer     NOT NULL,
  type        text        NOT NULL,
  title       text        NOT NULL,
  body        jsonb       NOT NULL DEFAULT '{}',
  is_read     boolean     NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT player_inbox_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT player_inbox_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX idx_inbox_game   ON player_inbox USING btree (game_id, tick DESC);
CREATE INDEX idx_inbox_player ON player_inbox USING btree (player_id, is_read, tick DESC);

-- ---------------------------------------------------------------------------
-- intel_snapshots  (per-tick summary of enemy intel)
-- ---------------------------------------------------------------------------
CREATE TABLE intel_snapshots (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint      NOT NULL,
  player_id           bigint      NOT NULL,
  tick                integer     NOT NULL,
  castles             integer     NOT NULL DEFAULT 0,
  troops              integer     NOT NULL DEFAULT 0,
  commanders          integer     NOT NULL DEFAULT 0,
  gold_level          integer     NOT NULL DEFAULT 0,
  industry_level      integer     NOT NULL DEFAULT 0,
  prestige_level      integer     NOT NULL DEFAULT 0,
  hand_level          integer     NOT NULL DEFAULT 0,
  coin_level          integer     NOT NULL DEFAULT 0,
  lord_commander_level integer    NOT NULL DEFAULT 0,
  whisperers_level    integer     NOT NULL DEFAULT 0,
  grand_maester_level integer     NOT NULL DEFAULT 0,
  laws_level          integer     NOT NULL DEFAULT 0,
  created_at          timestamptz          DEFAULT now(),
  CONSTRAINT intel_snapshots_game_id_player_id_tick_key UNIQUE (game_id, player_id, tick),
  CONSTRAINT intel_snapshots_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT intel_snapshots_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX intel_snapshots_game_tick ON intel_snapshots USING btree (game_id, tick);

-- ---------------------------------------------------------------------------
-- ledger  (gold transfers between players)
-- ---------------------------------------------------------------------------
CREATE TABLE ledger (
  id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id             bigint      NOT NULL,
  payer_player_id     bigint      NOT NULL,
  receiver_player_id  bigint      NOT NULL,
  amount              integer     NOT NULL,
  description         text,
  tick                integer     NOT NULL DEFAULT 0,
  is_forgiven         boolean     NOT NULL DEFAULT false,
  created_at          timestamptz          DEFAULT now(),
  CONSTRAINT ledger_amount_check            CHECK (amount > 0),
  CONSTRAINT ledger_game_id_fkey            FOREIGN KEY (game_id)           REFERENCES games       (id),
  CONSTRAINT ledger_payer_player_id_fkey    FOREIGN KEY (payer_player_id)   REFERENCES game_players (id),
  CONSTRAINT ledger_receiver_player_id_fkey FOREIGN KEY (receiver_player_id) REFERENCES game_players (id)
);

CREATE INDEX ledger_game_payer    ON ledger USING btree (game_id, payer_player_id);
CREATE INDEX ledger_game_receiver ON ledger USING btree (game_id, receiver_player_id);

-- ---------------------------------------------------------------------------
-- whispers  (AI-generated intelligence reports for a player)
-- ---------------------------------------------------------------------------
CREATE TABLE whispers (
  id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_id     integer     NOT NULL,
  player_id   integer     NOT NULL,
  tick        integer     NOT NULL,
  category    text        NOT NULL,
  confidence  integer     NOT NULL DEFAULT 50,
  body        jsonb       NOT NULL DEFAULT '{}',
  text        text,
  is_read     boolean     NOT NULL DEFAULT false,
  verified    boolean,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT whispers_game_id_fkey   FOREIGN KEY (game_id)   REFERENCES games       (id),
  CONSTRAINT whispers_player_id_fkey FOREIGN KEY (player_id) REFERENCES game_players (id)
);

CREATE INDEX whispers_game_player_tick_idx ON whispers USING btree (game_id, player_id, tick DESC);
